### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by mackyo** [Roboneet/Trebuchet.jl#5]
How does this ever learn anything it runs 1 time and stops. Where's the AI? Why do you guys put examples up and write articles about stuff that doesn't work. I'm reading your article "Reinforcement Learning vs. Differentiable Programming" . I'm sure this runs on version .04 or some thing like that. How is anybody supposed to learn this stuff if you guys don't update your programs. If you don't want to do that take the article down. It makes Julia and Flux look like it doen't really work. I'm losing faith in it. If every time you update everything stops workiing???? It's stupid.

**Comment by MikeInnes** [comment]
If something isn't working on your system, explaining the problem clearly will usually get you a solution. And if we don't know what the problem is then we can't help. What I can suggest is that you check out the instructions on activating Julia projects in the model-zoo, since they are designed to be reproducible and should reliably work on any Julia 1.0+.

Beyond that I don't see a question here that anyone can answer (sorry, no idea where the AI is, did you check behind the sofa?) so I'll close for now.

**Comment by mackyo** [comment]
From : https://github.com/FluxML/Trebuchet.jl

Trebuchet.grad([10.0, 1.0, 1.0])

Does not work, no such command as “grad”

**Comment by mackyo** [comment]
This is example.jl from Github

using Trebuchet

function Base.run(ws::Float64, r::Float64)
    t = TrebuchetState(;wind_speed=ws, release_angle=deg2rad(r))
    simulate(t)
    scope = visualise(t)

    if @isdefined(IJulia) || @isdefined(Juno)
      return scope
    elseif @isdefined(Blink)
      body!(Blink.Window(), scope)
    else
      println("to visualise, use Blink or run this on Juno or IJulia")
    end
end


run(-10.0, 33.2)  ### this only runs 1 time and stops.. no learning there


This is the front page on Github:

# using Blink # if not on Juno or IJulia
using Trebuchet

t = TrebuchetState()
simulate(t)

target = 100 # or nothing
s = visualise(t, target)

if @isdefined(Blink)
  body!(Blink.Window(), s)
end

# to find the gradient w.r.t (wind_speed, release_angle, weight)
Trebuchet.grad([10.0, 1.0, 1.0]) ### this doesn’t work


In the article on the Flux page: “The upshot is that we can take a simple simulator<https://github.com/Roboneet/Trebuchet.jl>, written in Julia and DiffEq<https://github.com/JuliaDiffEq/DifferentialEquations.jl> with no deep learning in mind, and get gradients for it in a single function call.”
Then you show: gradient(x -> 3x^2 + 2x + 1, 5) # (32,)
The only place I can find gradient is in Flux.tracker which is never used in the Github programs
Then you have:  gradient((wind, angle, weight) -> Trebuchet.shoot(wind, angle, weight), -2, 45, 200) # (4.02, -0.99, 0.051)
Which is not in any of the programs.

Then you say “After about five minutes of training (on a single core of my laptop’s CPU), it looks like this:” That’s the AI I’m talking about… what training?? It runs once

**Comment by MikeInnes** [comment]
The example from the readme is not the code the blog post was discussing (and I guess it's out of date too, which is unfortunate but easy to fix).

The code from the blog post is [here](https://github.com/FluxML/model-zoo/tree/master/games/differentiable-programming/trebuchet).

**Comment by mackyo** [comment]
Ok, I’ve been trying to make this work without asking a bunch of questions. I thought I might learn something if I stared at it long enough. DDPG.jl says :  Warning: Weight is too light …. I guess 99 times. DiffRL.jl says: meanloss() = 0.0 (tracked) a few times and stops.
I guess DIFFRL is training something, and maybe a parameter is set wrong on DDPG, but sorry, I don’t see how they fit together. And the visualize/simulate part is not there. The program looks cool, but it doesn’t look like it’s doing anything. I wish I had a better debugger so I could trace what it’s doing, but I don’t.
I must be missing something, maybe whole programs.. I’m lost, sorry --- mack

**Comment by MikeInnes** [comment]
Did you activate the Julia project in that folder?

**Comment by mackyo** [comment]
I think? I added : import Pkg; Pkg.activate()    at the top with all of the other using statements
