### ISSUE TITLE
s = visualise(t, target): Cannot `convert` an object of type JSExpr.JSString to an object of type String

### ISSUE THREAD

**Issue by bjce** [Roboneet/Trebuchet.jl#7]
First of all thank you very much for writing the package!
I tried to run the example given in the documentation of the package in `Julia 1.3`:

after having run:
```
pkg> add https://github.com/FluxML/Trebuchet.jl
```
I ran:

```
using Trebuchet

t = TrebuchetState()
simulate(t)

target = 100 # or nothing
s = visualise(t, target)

if @isdefined(Blink)
  body!(Blink.Window(), s)
end
```
But got the following error message:

```
ERROR: MethodError: Cannot `convert` an object of type JSExpr.JSString to an object of type String
Closest candidates are:
  convert(::Type{T}, ::T) where T<:AbstractString at strings/basic.jl:208
  convert(::Type{T}, ::AbstractString) where T<:AbstractString at strings/basic.jl:209
  convert(::Type{T}, ::T) where T at essentials.jl:168
Stacktrace:
 [1] WebIO.JSString(::JSExpr.JSString) at /Users/mymac/.julia/packages/WebIO/2nnB1/src/syntax.jl:54
 [2] onimport(::WebIO.Scope, ::JSExpr.JSString) at /Users/mymac/.julia/packages/WebIO/2nnB1/src/scope.jl:322
 [3] visualise(::TrebuchetState, ::Int64) at /Users/mymac/.julia/packages/Trebuchet/dU16T/src/visualise.jl:30
 [4] top-level scope at REPL[10]:1
```
The line `s = visualise(t, target)` seems to cause the problem

Do you have an idea of what I'am doing wrong / what went wrong?
Many thanks in advance for your support

**Comment by Roboneet** [comment]
I can't reproduce the error on `Julia 1.3.0`. Can you try this on master branch?
```julia
pkg> add https://github.com/FluxML/Trebuchet.jl#master
```

**Comment by bjce** [comment]
Thank you very much for your answer @Roboneet. I retried the code and it worked flawlessly. I also had some similar trouble with other package recently. I don't know what happened but now it works. Sorry for the hassle
