### ISSUE TITLE
Update links

### ISSUE THREAD

**Issue by schlichtanders** [Roboneet/Trebuchet.jl#9]
The link in the blog-post https://fluxml.ai/2019/03/05/dp-vs-rl.html
as well as the links in [this README.md](https://github.com/FluxML/Trebuchet.jl/blob/master/README.md)
```
Note:
The code corresponding to this blog post can be found here
```

Are pointing towards old code https://github.com/FluxML/model-zoo/blob/10bd26ca21079b1c6ee246dd1938beab55178949/games/differentiable-programming/trebuchet/DiffRL.jl

That code is no longer working, and hence it should be pointed to the more current version https://github.com/FluxML/model-zoo/tree/master/contrib/games/differentiable-programming/trebuchet

**Comment by asuresh213** [comment]
Running the current version raises the following error.  

`ERROR: LoadError: Compiling Tuple{typeof(Trebuchet.shoot),Tuple{Float64,Float64,Float64}}: try/catch is not supported.`

(Most likely rising from the computing the gradient inside of Flux.train!)

```julia 
Flux.gradient((wind, ang, mass) -> Trebuchet.shoot(wind, ang, mass)[2], -2.0, 45.0, 200.0)
```
from the blog post also returns the same error. 

`ERROR: LoadError: Compiling Tuple{typeof(Trebuchet.shoot),Tuple{Float64,Float64,Float64}}: try/catch is not supported.`

**Comment by Roboneet** [comment]
The current version raises the error because computing gradient inside a `try/catch` is not supported. It's best to keep track of that issue in model zoo as the code resides there

**Comment by schlichtanders** [comment]
the post from @asuresh213  was completely unrelated to my original question. @asuresh213 Please don't hijack other person's issues. 

Anyway, @Roboneet  can you update the links, at least in this repo's README respectively?
Of course it would also be great to update the link in the original blog post. Do you know where to address this?

**Comment by asuresh213** [comment]
???? @schlichtanders 
Running the [current version](https://github.com/FluxML/model-zoo/tree/master/contrib/games/differentiable-programming/trebuchet) that you pointed to, raises try/catch errors. The code from the link you posted is not working. That's all I was trying to get across.

**Comment by schlichtanders** [comment]
@asuresh213  sorry for misunderstanding, you tried this code https://github.com/FluxML/model-zoo/tree/master/contrib/games/differentiable-programming/trebuchet, especially https://github.com/FluxML/model-zoo/blob/master/contrib/games/differentiable-programming/trebuchet/DiffRL.jl and it didn't work for you when instantiating the manifest.toml?

It worked for me.

Also the try/catch is taken care of in the use of forwarddiff, so I am confused

**Comment by Roboneet** [comment]
@schlichtanders The blog post is [here](https://github.com/FluxML/fluxml.github.io). I forgot to mention, but the link in the README is updated.

**Comment by schlichtanders** [comment]
@Roboneet thanks a lot, I will open a similar ticket on the blogpost github then
